supported_command_classes:
  - name: "COMMAND_CLASS_BASIC"
    version: 2
    mqtt_support: true
    support: false
    control: true
    interview_attributes:
      - "Current Value"
    minimal_scheme: ZWAVE_CONTROLLER_ENCAPSULATION_NETWORK_SCHEME
  - name: "COMMAND_CLASS_BATTERY"
    version: 3
    mqtt_support: true
    support: false
    control: true
    interview_attributes:
      - "Battery Level"
    minimal_scheme: ZWAVE_CONTROLLER_ENCAPSULATION_NETWORK_SCHEME
  - name: "COMMAND_CLASS_SWITCH_BINARY"
    version: 2
    mqtt_support: true
    support: false
    control: true
    interview_attributes:
      - "Current Value"
    minimal_scheme: ZWAVE_CONTROLLER_ENCAPSULATION_NONE
  - name: "COMMAND_CLASS_VERSION"
    version: 3
    mqtt_support: true
    support: true
    control: true
    interview_attributes: []
    minimal_scheme: ZWAVE_CONTROLLER_ENCAPSULATION_NETWORK_SCHEME
  - name: "COMMAND_CLASS_SUPERVISION"
    version: 2
    mqtt_support: false
    support: true
    control: true
    interview_attributes: []
    minimal_scheme: ZWAVE_CONTROLLER_ENCAPSULATION_NONE
    manual_security_validation: true
  - name: "COMMAND_CLASS_MANUFACTURER_SPECIFIC"
    version: 2
    mqtt_support: true
    support: true
    control: true
    interview_attributes: []
    minimal_scheme: ZWAVE_CONTROLLER_ENCAPSULATION_NETWORK_SCHEME
  - name: "COMMAND_CLASS_DEVICE_RESET_LOCALLY"
    version: 1
    mqtt_support: false
    support: true
    control: true
    minimal_scheme: ZWAVE_CONTROLLER_ENCAPSULATION_NETWORK_SCHEME
  - name: "COMMAND_CLASS_ZWAVEPLUS_INFO"
    version: 2
    mqtt_support: false
    support: true
    control: true
    interview_attributes: []
    minimal_scheme: ZWAVE_CONTROLLER_ENCAPSULATION_NONE
  - name: "COMMAND_CLASS_POWERLEVEL"
    version: 1
    mqtt_support: false
    support: true
    control: false
    interview_attributes: []
    minimal_scheme: ZWAVE_CONTROLLER_ENCAPSULATION_NETWORK_SCHEME
  - name: "COMMAND_CLASS_MULTI_CHANNEL_ASSOCIATION"
    version: 5
    mqtt_support: true
    support: true
    control: true
    interview_attributes: []
    minimal_scheme: ZWAVE_CONTROLLER_ENCAPSULATION_NETWORK_SCHEME
  - name: "COMMAND_CLASS_MULTI_CMD"
    version: 1
    mqtt_support: false
    support: true
    control: true
    interview_attributes: []
    minimal_scheme: ZWAVE_CONTROLLER_ENCAPSULATION_NONE
  - name: "COMMAND_CLASS_ASSOCIATION"
    version: 4
    mqtt_support: true
    support: true
    control: true
    interview_attributes: []
    minimal_scheme: ZWAVE_CONTROLLER_ENCAPSULATION_NETWORK_SCHEME
  - name: "COMMAND_CLASS_MULTI_CHANNEL"
    version: 4
    mqtt_support: true
    support: false
    control: true
    has_endpoints: true
    interview_attributes: []
    minimal_scheme: ZWAVE_CONTROLLER_ENCAPSULATION_NETWORK_SCHEME
  - name: "COMMAND_CLASS_INDICATOR"
    version: 4
    mqtt_support: true
    support: true
    control: true
    interview_attributes: []
    minimal_scheme: ZWAVE_CONTROLLER_ENCAPSULATION_NETWORK_SCHEME
  - name: "COMMAND_CLASS_WAKE_UP"
    version: 3
    mqtt_support: true
    support: false
    control: true
    interview_attributes: []
    minimal_scheme: ZWAVE_CONTROLLER_ENCAPSULATION_NETWORK_SCHEME
  - name: "COMMAND_CLASS_THERMOSTAT_MODE"
    version: 3
    mqtt_support: true
    support: false
    control: true
    interview_attributes: []
    minimal_scheme: ZWAVE_CONTROLLER_ENCAPSULATION_NETWORK_SCHEME
  - name: "COMMAND_CLASS_THERMOSTAT_SETPOINT"
    version: 3
    mqtt_support: true
    support: false
    control: true
    interview_attributes: []
    minimal_scheme: ZWAVE_CONTROLLER_ENCAPSULATION_NETWORK_SCHEME
  - name: "COMMAND_CLASS_THERMOSTAT_FAN_MODE"
    version: 5
    mqtt_support: true
    support: false
    control: true
    interview_attributes: []
    minimal_scheme: ZWAVE_CONTROLLER_ENCAPSULATION_NETWORK_SCHEME
  - name: "COMMAND_CLASS_SWITCH_COLOR"
    version: 3
    mqtt_support: true
    support: false
    control: true
    interview_attributes:
      - "Color Component mask"
    minimal_scheme: ZWAVE_CONTROLLER_ENCAPSULATION_NETWORK_SCHEME
  - name: "COMMAND_CLASS_NOTIFICATION"
    deprecated_names: ["COMMAND_CLASS_ALARM"]
    version: 8
    mqtt_support: true
    support: false
    control: true
    interview_attributes:
      - "Bit Mask"
    minimal_scheme: ZWAVE_CONTROLLER_ENCAPSULATION_NETWORK_SCHEME
  - name: "COMMAND_CLASS_SWITCH_MULTILEVEL"
    version: 4
    mqtt_support: true
    support: false
    control: true
    interview_attributes:
      - "Current Value"
    minimal_scheme: ZWAVE_CONTROLLER_ENCAPSULATION_NONE
  - name: "COMMAND_CLASS_DOOR_LOCK"
    version: 4
    mqtt_support: true
    support: false
    control: true
    interview_attributes:
      - "Current Door Lock Mode"
    minimal_scheme: ZWAVE_CONTROLLER_ENCAPSULATION_NETWORK_SCHEME
  - name: "COMMAND_CLASS_FIRMWARE_UPDATE_MD"
    version: 5
    mqtt_support: false
    support: true
    control: true
    interview_attributes: []
    minimal_scheme: ZWAVE_CONTROLLER_ENCAPSULATION_NETWORK_SCHEME
  - name: "COMMAND_CLASS_TIME"
    version: 3
    mqtt_support: false
    support: true
    control: false
    interview_attributes: []
    minimal_scheme: ZWAVE_CONTROLLER_ENCAPSULATION_NONE
    manual_security_validation: true

  - name: "COMMAND_CLASS_ASSOCIATION_GRP_INFO"
    version: 3
    mqtt_support: true
    support: true
    control: true
    interview_attributes:
      - "Grouping Identifier"
    minimal_scheme: ZWAVE_CONTROLLER_ENCAPSULATION_NETWORK_SCHEME

  - name: "COMMAND_CLASS_INCLUSION_CONTROLLER"
    version: 1
    mqtt_support: false
    support: true
    control: true
    interview_attributes: []
    minimal_scheme: ZWAVE_CONTROLLER_ENCAPSULATION_NONE

  - name: "COMMAND_CLASS_SECURITY"
    version: 1
    mqtt_support: false
    protocol: true
    support: true
    control: true
    manual_security_validation: true
    generate_commands:
      - SECURITY_COMMANDS_SUPPORTED_GET
      - SECURITY_COMMANDS_SUPPORTED_REPORT
    minimal_scheme: ZWAVE_CONTROLLER_ENCAPSULATION_NONE

  - name: "COMMAND_CLASS_SECURITY_2"
    version: 2
    mqtt_support: false
    protocol: true
    support: true
    control: true
    generate_commands:
      - SECURITY_2_COMMANDS_SUPPORTED_GET
      - SECURITY_2_COMMANDS_SUPPORTED_REPORT
    minimal_scheme: ZWAVE_CONTROLLER_ENCAPSULATION_NONE

  - name: "ZWAVE_CMD_CLASS"
    version: 1
    mqtt_support: false
    protocol: true
    support: true
    control: false
    generate_commands: []
    minimal_scheme: ZWAVE_CONTROLLER_ENCAPSULATION_NETWORK_SCHEME

  - name: "COMMAND_CLASS_ZWAVE_LONG_RANGE"
    version: 1
    mqtt_support: false
    protocol: true
    support: true
    control: false
    generate_commands: []
    minimal_scheme: ZWAVE_CONTROLLER_ENCAPSULATION_NETWORK_SCHEME

  - name: "COMMAND_CLASS_TRANSPORT_SERVICE"
    version: 2
    mqtt_support: false
    protocol: true
    support: true
    control: true
    generate_commands: []
    minimal_scheme: ZWAVE_CONTROLLER_ENCAPSULATION_NONE

optional_param_overrides:
  - command_class: "COMMAND_CLASS_NOTIFICATION"
    command: "NOTIFICATION_REPORT"
    param: "Sequence Number"
    optionaloffs: "0x06"
    optionalmask: "0x80"
