/******************************************************************************
 * # License
 * <b>Copyright 2021 Silicon Laboratories Inc. www.silabs.com</b>
 ******************************************************************************
 * The licensor of this software is Silicon Laboratories Inc. Your use of this
 * software is governed by the terms of Silicon Labs Master Software License
 * Agreement (MSLA) available at
 * www.silabs.com/about-us/legal/master-software-license-agreement. This
 * software is distributed to you in Source Code format and is governed by the
 * sections of the MSLA applicable to Source Code.
 *
 *****************************************************************************/
// Includes from this component
#include "zpc_attribute_store_all_ids.h"
// ZPC components
#include "attribute_store_type_registration.h"
#include "zpc_attribute_store_type_registration.h"
#include <vector>
// defines
#define UNSIGNED_LONG_STORAGE_TYPE ((sizeof(unsigned long) == sizeof(uint32_t)) ? U32_STORAGE_TYPE : U64_STORAGE_TYPE)

// clang-format off
static const std::vector<attribute_schema_t> attribute_schema = {
  {ATTRIBUTE_TREE_ROOT,   "Root node",   ATTRIBUTE_STORE_INVALID_ATTRIBUTE_TYPE,   EMPTY_STORAGE_TYPE},
  // Generic Z-Wave attributes
  {ATTRIBUTE_HOME_ID, "HomeID", ATTRIBUTE_TREE_ROOT, BYTE_ARRAY_STORAGE_TYPE},
  {ATTRIBUTE_NODE_ID, "NodeID", ATTRIBUTE_HOME_ID, U16_STORAGE_TYPE},
  {ATTRIBUTE_ENDPOINT_ID, "Endpoint ID", ATTRIBUTE_NODE_ID, U8_STORAGE_TYPE},
  {ATTRIBUTE_GRANTED_SECURITY_KEYS,   "Granted keys",   ATTRIBUTE_NODE_ID,   U8_STORAGE_TYPE},
  {ATTRIBUTE_KEX_FAIL_TYPE,   "KEX Fail type",   ATTRIBUTE_NODE_ID,   U32_STORAGE_TYPE},
  {ATTRIBUTE_S2_DSK, "S2 DSK", ATTRIBUTE_NODE_ID, BYTE_ARRAY_STORAGE_TYPE},
  {ATTRIBUTE_ZWAVE_PROTOCOL_LISTENING,   "NIF: Protocol Listening byte",   ATTRIBUTE_NODE_ID,   U8_STORAGE_TYPE},
  {ATTRIBUTE_ZWAVE_OPTIONAL_PROTOCOL,   "NIF: Optional Protocol byte",   ATTRIBUTE_NODE_ID,   U8_STORAGE_TYPE},
  {ATTRIBUTE_ZWAVE_ROLE_TYPE,   "Role Type",   ATTRIBUTE_NODE_ID,   ENUM_STORAGE_TYPE},
  {ATTRIBUTE_NODE_NAME, "Node Name", ATTRIBUTE_NODE_ID, C_STRING_STORAGE_TYPE},
  {ATTRIBUTE_NODE_LOCATION,   "Node Location",   ATTRIBUTE_NODE_ID,   C_STRING_STORAGE_TYPE},
  {ATTRIBUTE_LAST_RECEIVED_FRAME_TIMESTAMP,   "Last Rx/Tx timestamp",   ATTRIBUTE_NODE_ID,   UNSIGNED_LONG_STORAGE_TYPE},
  {ATTRIBUTE_LAST_RX_RSSI,   "Last RX RSSI",   ATTRIBUTE_NODE_ID,   I8_STORAGE_TYPE},
  {ATTRIBUTE_LAST_ROUTING_PATH,   "Last routing path",   ATTRIBUTE_NODE_ID,   BYTE_ARRAY_STORAGE_TYPE},
  {ATTRIBUTE_LAST_TX_TICKS,   "Last TX ticks",   ATTRIBUTE_NODE_ID,   U16_STORAGE_TYPE},
  {ATTRIBUTE_LAST_NUMBER_OF_REPEATERS,   "Last number of repeaters",   ATTRIBUTE_NODE_ID,   U8_STORAGE_TYPE},
  {ATTRIBUTE_LAST_TX_POWER,   "Last TX power",   ATTRIBUTE_NODE_ID,   I8_STORAGE_TYPE},
  {ATTRIBUTE_ZWAVE_INCLUSION_PROTOCOL,   "Inclusion protocol",   ATTRIBUTE_NODE_ID,   ENUM_STORAGE_TYPE},
  {ATTRIBUTE_NODE_IS_S2_CAPABLE,   "Node has S2 capability",   ATTRIBUTE_NODE_ID,   EMPTY_STORAGE_TYPE},
  {ATTRIBUTE_ZWAVE_NLS_SUPPORT,   "NLS support",   ATTRIBUTE_NODE_ID,   U8_STORAGE_TYPE},
  {ATTRIBUTE_ZWAVE_NLS_STATE,   "NLS state",   ATTRIBUTE_NODE_ID,   U8_STORAGE_TYPE},
  {ATTRIBUTE_POLL_ENGINE_MARK,   "Poll Engine Mark",   ATTRIBUTE_STORE_INVALID_ATTRIBUTE_TYPE,   UNKNOWN_STORAGE_TYPE},
  /////////////////////////////////////////////////////////////////////
  //         Generic Z-Wave Endpoint ID attributes
  /////////////////////////////////////////////////////////////////////
  {ATTRIBUTE_ZWAVE_NIF, "NIF <DEPRECATED>", ATTRIBUTE_ENDPOINT_ID, BYTE_ARRAY_STORAGE_TYPE},
  {ATTRIBUTE_ZWAVE_SECURE_NIF,   "S2 Capabilities <DEPRECATED>",   ATTRIBUTE_ENDPOINT_ID,   BYTE_ARRAY_STORAGE_TYPE},
  {ATTRIBUTE_ZWAVE_BASIC_DEVICE_CLASS,   "Basic Device Class <DEPRECATED>",   ATTRIBUTE_ENDPOINT_ID,   U8_STORAGE_TYPE},
  {ATTRIBUTE_ZWAVE_GENERIC_DEVICE_CLASS,   "Generic Device Class <DEPRECATED>",   ATTRIBUTE_ENDPOINT_ID,   U8_STORAGE_TYPE},
  {ATTRIBUTE_ZWAVE_SPECIFIC_DEVICE_CLASS,   "Specific Device Class <DEPRECATED>",   ATTRIBUTE_ENDPOINT_ID,   U8_STORAGE_TYPE},
  {ATTRIBUTE_ZWAVE_KEY_AND_PROTOCOL_TO_DISCOVER,   "Network Key / Protocol to probe",   ATTRIBUTE_ENDPOINT_ID,   BYTE_ARRAY_STORAGE_TYPE},
  /////////////////////////////////////////////////////////////////////
  //        Alarm Sensor Command Class attributes
  /////////////////////////////////////////////////////////////////////
  {ATTRIBUTE_COMMAND_CLASS_ALARM_SENSOR_BITMASK,   "Alarm Sensor Bitmask",   ATTRIBUTE_ENDPOINT_ID,   BYTE_ARRAY_STORAGE_TYPE},
  {ATTRIBUTE_COMMAND_CLASS_ALARM_SENSOR_TYPE,   "Alarm Sensor Type",   ATTRIBUTE_ENDPOINT_ID,   U8_STORAGE_TYPE},
  {ATTRIBUTE_COMMAND_CLASS_ALARM_SENSOR_STATE,   "State",   ATTRIBUTE_COMMAND_CLASS_ALARM_SENSOR_TYPE,   U8_STORAGE_TYPE},
  {ATTRIBUTE_COMMAND_CLASS_ALARM_SENSOR_NODE_ID,   "NodeID",   ATTRIBUTE_COMMAND_CLASS_ALARM_SENSOR_TYPE,   U16_STORAGE_TYPE},
  {ATTRIBUTE_COMMAND_CLASS_ALARM_SENSOR_SECONDS,   "Seconds",   ATTRIBUTE_COMMAND_CLASS_ALARM_SENSOR_TYPE,   U16_STORAGE_TYPE},
  /////////////////////////////////////////////////////////////////////
  //        Barrier Operator Command Class attributes
  /////////////////////////////////////////////////////////////////////
  {ATTRIBUTE_COMMAND_CLASS_BARRIER_OPERATOR_BITMASK,   "Barrier Operator Bitmask",   ATTRIBUTE_ENDPOINT_ID,   BYTE_ARRAY_STORAGE_TYPE},
  {ATTRIBUTE_COMMAND_CLASS_BARRIER_OPERATOR_STATE,   "Barrier Operator State",   ATTRIBUTE_ENDPOINT_ID,   U8_STORAGE_TYPE},
  {ATTRIBUTE_COMMAND_CLASS_BARRIER_OPERATOR_SUBSYSTEM_TYPE,   "Subsystem Type",   ATTRIBUTE_ENDPOINT_ID,   U8_STORAGE_TYPE},
  {ATTRIBUTE_COMMAND_CLASS_BARRIER_OPERATOR_SUBSYSTEM_STATE,   "Subsystem State",   ATTRIBUTE_COMMAND_CLASS_BARRIER_OPERATOR_SUBSYSTEM_TYPE,   U8_STORAGE_TYPE},
  /////////////////////////////////////////////////////////////////////
  //        Central Scene Command Class attributes
  /////////////////////////////////////////////////////////////////////
  {ATTRIBUTE_COMMAND_CLASS_CENTRAL_SCENE_NUMBER_OF_SCENES,   "Number of Scenes",   ATTRIBUTE_ENDPOINT_ID,   U32_STORAGE_TYPE},
  {ATTRIBUTE_COMMAND_CLASS_CENTRAL_SCENE_MAX_KEY_ATTRIBUTE,   "Maximum Key Attributes",   ATTRIBUTE_ENDPOINT_ID,   U8_STORAGE_TYPE},
  {ATTRIBUTE_COMMAND_CLASS_CENTRAL_SCENE_SLOW_REFRESH,   "Central Scene Slow Refresh",   ATTRIBUTE_ENDPOINT_ID,   U8_STORAGE_TYPE},
  {ATTRIBUTE_COMMAND_CLASS_CENTRAL_SCENE_ACTIVE_SCENE,   "Central Scene Active Scene",   ATTRIBUTE_ENDPOINT_ID,   U32_STORAGE_TYPE},
  {ATTRIBUTE_COMMAND_CLASS_CENTRAL_SCENE_ACTIVE_SCENE_SEQUENCE_NUMBER,   "Sequence Number",   ATTRIBUTE_COMMAND_CLASS_CENTRAL_SCENE_ACTIVE_SCENE,   U8_STORAGE_TYPE},
  /////////////////////////////////////////////////////////////////////
  //         Configuration Command Class attributes
  /////////////////////////////////////////////////////////////////////
  {ATTRIBUTE_COMMAND_CLASS_CONFIGURATION_VERSION,   "Configuration Command Class version",   ATTRIBUTE_ENDPOINT_ID,   U8_STORAGE_TYPE},
  {ATTRIBUTE_COMMAND_CLASS_CONFIGURATION_NEXT_SUPPORTED_PARAMETER_ID,   "Next Configuration Parameter ID",   ATTRIBUTE_ENDPOINT_ID,   U16_STORAGE_TYPE},
  {ATTRIBUTE_COMMAND_CLASS_CONFIGURATION_BULK_SUPPORT,   "Configuration Bulk Support",   ATTRIBUTE_ENDPOINT_ID,   U8_STORAGE_TYPE},
  {ATTRIBUTE_COMMAND_CLASS_CONFIGURATION_PARAMETER_ID,   "Configuration Parameter ID",   ATTRIBUTE_STORE_INVALID_ATTRIBUTE_TYPE,   U16_STORAGE_TYPE},
  {ATTRIBUTE_COMMAND_CLASS_CONFIGURATION_PARAMETER_SIZE,   "Size",   ATTRIBUTE_COMMAND_CLASS_CONFIGURATION_PARAMETER_ID,   U8_STORAGE_TYPE},
  {ATTRIBUTE_COMMAND_CLASS_CONFIGURATION_PARAMETER_FORMAT,   "Format",   ATTRIBUTE_COMMAND_CLASS_CONFIGURATION_PARAMETER_ID,   U8_STORAGE_TYPE},
  {ATTRIBUTE_COMMAND_CLASS_CONFIGURATION_PARAMETER_NAME,   "Name",   ATTRIBUTE_COMMAND_CLASS_CONFIGURATION_PARAMETER_ID,   C_STRING_STORAGE_TYPE},
  {ATTRIBUTE_COMMAND_CLASS_CONFIGURATION_PARAMETER_INFO,   "Info",   ATTRIBUTE_COMMAND_CLASS_CONFIGURATION_PARAMETER_ID,   C_STRING_STORAGE_TYPE},
  {ATTRIBUTE_COMMAND_CLASS_CONFIGURATION_PARAMETER_VALUE,   "Value",   ATTRIBUTE_COMMAND_CLASS_CONFIGURATION_PARAMETER_ID,   I64_STORAGE_TYPE},
  {ATTRIBUTE_COMMAND_CLASS_CONFIGURATION_PARAMETER_MIN_VALUE,   "Min Value",   ATTRIBUTE_COMMAND_CLASS_CONFIGURATION_PARAMETER_ID,   I64_STORAGE_TYPE},
  {ATTRIBUTE_COMMAND_CLASS_CONFIGURATION_PARAMETER_MAX_VALUE,   "Max Value",   ATTRIBUTE_COMMAND_CLASS_CONFIGURATION_PARAMETER_ID,   I64_STORAGE_TYPE},
  {ATTRIBUTE_COMMAND_CLASS_CONFIGURATION_PARAMETER_DEFAULT_VALUE,   "Default Value",   ATTRIBUTE_COMMAND_CLASS_CONFIGURATION_PARAMETER_ID,   I64_STORAGE_TYPE},
  {ATTRIBUTE_COMMAND_CLASS_CONFIGURATION_PARAMETER_ADVANCED,   "Advanced flag",   ATTRIBUTE_COMMAND_CLASS_CONFIGURATION_PARAMETER_ID,   U8_STORAGE_TYPE},
  {ATTRIBUTE_COMMAND_CLASS_CONFIGURATION_PARAMETER_READ_ONLY,   "Read-only flag",   ATTRIBUTE_COMMAND_CLASS_CONFIGURATION_PARAMETER_ID,   U8_STORAGE_TYPE},
  {ATTRIBUTE_COMMAND_CLASS_CONFIGURATION_PARAMETER_ALTERING_CAPABILITIES,   "Altering capabilities flag",   ATTRIBUTE_COMMAND_CLASS_CONFIGURATION_PARAMETER_ID,   U8_STORAGE_TYPE},
  {ATTRIBUTE_COMMAND_CLASS_CONFIGURATION_DEFAULT_RESET_REQUESTED,   "Configuration Default Reset requested",   ATTRIBUTE_ENDPOINT_ID,   ENUM_STORAGE_TYPE},
  {ATTRIBUTE_COMMAND_CLASS_CONFIGURATION_PARAMETERS_TO_DISCOVER,   "List of Configuration Parameters ID to discover",   ATTRIBUTE_ENDPOINT_ID,   EMPTY_STORAGE_TYPE},
  /////////////////////////////////////////////////////////////////////
  // CRC16 Command Class attributes
  /////////////////////////////////////////////////////////////////////
  {ATTRIBUTE_COMMAND_CLASS_CRC16_VERSION,   "CRC16 Version",   ATTRIBUTE_ENDPOINT_ID,   U8_STORAGE_TYPE},
  {ATTRIBUTE_COMMAND_CLASS_CRC16_DISABLE_CRC16, "Disable CRC16 frames", ATTRIBUTE_ENDPOINT_ID, U8_STORAGE_TYPE},
  /////////////////////////////////////////////////////////////////////
  // Humidity Control Setpoint Command Class attributes
  /////////////////////////////////////////////////////////////////////
  {ATTRIBUTE_COMMAND_CLASS_HUMIDITY_CONTROL_SETPOINT_VERSION,   "Humidity Control Setpoint Version",   ATTRIBUTE_ENDPOINT_ID,   U8_STORAGE_TYPE},
  {ATTRIBUTE_COMMAND_CLASS_HUMIDITY_CONTROL_SETPOINT_SUPPORTED_TYPES,   "Humidity Control Supported Setpoint Types",   ATTRIBUTE_ENDPOINT_ID,   U8_STORAGE_TYPE},
  {ATTRIBUTE_COMMAND_CLASS_HUMIDITY_CONTROL_SETPOINT_TYPE,   "Humidity Control Setpoint Type",   ATTRIBUTE_ENDPOINT_ID,   U8_STORAGE_TYPE},
  {ATTRIBUTE_COMMAND_CLASS_HUMIDITY_CONTROL_SETPOINT_SUPPORTED_SCALE,   "Humidity Control Supported Scales",   ATTRIBUTE_ENDPOINT_ID,   U8_STORAGE_TYPE},
  {ATTRIBUTE_COMMAND_CLASS_HUMIDITY_CONTROL_SETPOINT_VALUE,   "Value",   ATTRIBUTE_COMMAND_CLASS_HUMIDITY_CONTROL_SETPOINT_TYPE,   I32_STORAGE_TYPE},
  {ATTRIBUTE_COMMAND_CLASS_HUMIDITY_CONTROL_SETPOINT_VALUE_SCALE,   "Value Scale",   ATTRIBUTE_COMMAND_CLASS_HUMIDITY_CONTROL_SETPOINT_VALUE,   U8_STORAGE_TYPE},
  {ATTRIBUTE_COMMAND_CLASS_HUMIDITY_CONTROL_SETPOINT_VALUE_PRECISION, "Value Precision",   ATTRIBUTE_COMMAND_CLASS_HUMIDITY_CONTROL_SETPOINT_VALUE,   U8_STORAGE_TYPE},
  {ATTRIBUTE_COMMAND_CLASS_HUMIDITY_CONTROL_SETPOINT_MIN_VALUE,   "Min Value",   ATTRIBUTE_COMMAND_CLASS_HUMIDITY_CONTROL_SETPOINT_TYPE,   I32_STORAGE_TYPE},
  {ATTRIBUTE_COMMAND_CLASS_HUMIDITY_CONTROL_SETPOINT_MIN_VALUE_SCALE,   "Min Value Scale",   ATTRIBUTE_COMMAND_CLASS_HUMIDITY_CONTROL_SETPOINT_MIN_VALUE,   U8_STORAGE_TYPE},
  {ATTRIBUTE_COMMAND_CLASS_HUMIDITY_CONTROL_SETPOINT_MIN_VALUE_PRECISION, "Min Value Precision",   ATTRIBUTE_COMMAND_CLASS_HUMIDITY_CONTROL_SETPOINT_MIN_VALUE,   U8_STORAGE_TYPE},
  {ATTRIBUTE_COMMAND_CLASS_HUMIDITY_CONTROL_SETPOINT_MAX_VALUE,   "Max Value",   ATTRIBUTE_COMMAND_CLASS_HUMIDITY_CONTROL_SETPOINT_TYPE,   I32_STORAGE_TYPE},
  {ATTRIBUTE_COMMAND_CLASS_HUMIDITY_CONTROL_SETPOINT_MAX_VALUE_SCALE,   "Max Value Scale",   ATTRIBUTE_COMMAND_CLASS_HUMIDITY_CONTROL_SETPOINT_MAX_VALUE,   U8_STORAGE_TYPE},
  {ATTRIBUTE_COMMAND_CLASS_HUMIDITY_CONTROL_SETPOINT_MAX_VALUE_PRECISION, "Max Value Precision",   ATTRIBUTE_COMMAND_CLASS_HUMIDITY_CONTROL_SETPOINT_MAX_VALUE,   U8_STORAGE_TYPE},
  /////////////////////////////////////////////////////////////////////
  //         Meter Command Class attributes
  /////////////////////////////////////////////////////////////////////
  {ATTRIBUTE_COMMAND_CLASS_METER_VERSION,   "Meter Version",   ATTRIBUTE_ENDPOINT_ID,   U8_STORAGE_TYPE},
  {ATTRIBUTE_COMMAND_CLASS_METER_RESET_SUPPORTED,   "Meter Reset supported",   ATTRIBUTE_ENDPOINT_ID,   U8_STORAGE_TYPE},
  {ATTRIBUTE_COMMAND_CLASS_METER_SUPPORTED_SCALES,   "Meter Supported Scales",   ATTRIBUTE_ENDPOINT_ID,   BYTE_ARRAY_STORAGE_TYPE},
  {ATTRIBUTE_COMMAND_CLASS_METER_SUPPORTED_RATE_TYPES,   "Meter Supported Rate Types",   ATTRIBUTE_ENDPOINT_ID,   U8_STORAGE_TYPE},
  // Meter type can be either under the Endpoint or under the Reset requested
  {ATTRIBUTE_COMMAND_CLASS_METER_TYPE,   "Meter Type",   ATTRIBUTE_ENDPOINT_ID,   U8_STORAGE_TYPE},
  {ATTRIBUTE_COMMAND_CLASS_METER_SCALE,   "Scale",   ATTRIBUTE_COMMAND_CLASS_METER_TYPE,   U16_STORAGE_TYPE},
  {ATTRIBUTE_COMMAND_CLASS_METER_RATE_TYPE,   "Rate Type",   ATTRIBUTE_COMMAND_CLASS_METER_SCALE,   U8_STORAGE_TYPE},
  {ATTRIBUTE_COMMAND_CLASS_METER_VALUE,   "Value",   ATTRIBUTE_COMMAND_CLASS_METER_RATE_TYPE,   I32_STORAGE_TYPE},
  {ATTRIBUTE_COMMAND_CLASS_METER_PRECISION,   "Precision",   ATTRIBUTE_COMMAND_CLASS_METER_RATE_TYPE,   U8_STORAGE_TYPE},
  /////////////////////////////////////////////////////////////////////
  //        Multilevel Sensor Command Class attributes
  /////////////////////////////////////////////////////////////////////
  {ATTRIBUTE_COMMAND_CLASS_SENSOR_MULTILEVEL_VERSION,   "Multilevel Sensor Command Class version",   ATTRIBUTE_ENDPOINT_ID,   U8_STORAGE_TYPE},
  {ATTRIBUTE_COMMAND_CLASS_SENSOR_MULTILEVEL_SENSOR_TYPE,   "Multilevel Sensor Type",   ATTRIBUTE_ENDPOINT_ID,   U8_STORAGE_TYPE},
  {ATTRIBUTE_COMMAND_CLASS_SENSOR_MULTILEVEL_SUPPORTED_SCALES,   "Supported Scales",   ATTRIBUTE_COMMAND_CLASS_SENSOR_MULTILEVEL_SENSOR_TYPE,   U8_STORAGE_TYPE},
  {ATTRIBUTE_COMMAND_CLASS_SENSOR_MULTILEVEL_SCALE,   "Scale",   ATTRIBUTE_COMMAND_CLASS_SENSOR_MULTILEVEL_SENSOR_TYPE,   I32_STORAGE_TYPE},
  {ATTRIBUTE_COMMAND_CLASS_SENSOR_MULTILEVEL_SENSOR_VALUE,   "Value",   ATTRIBUTE_COMMAND_CLASS_SENSOR_MULTILEVEL_SENSOR_TYPE,   I32_STORAGE_TYPE},
  {ATTRIBUTE_COMMAND_CLASS_SENSOR_MULTILEVEL_SUPPORTED_SENSOR_TYPES,   "Multilevel Sensor Supported Sensor Types",   ATTRIBUTE_ENDPOINT_ID,   BYTE_ARRAY_STORAGE_TYPE},
  /////////////////////////////////////////////////////////////////////
  //         Scene Activation Command Class attributes
  /////////////////////////////////////////////////////////////////////
  {ATTRIBUTE_COMMAND_CLASS_SCENE_ACTIVATION_VERSION,   "Scene Activation Command Class Version",   ATTRIBUTE_ENDPOINT_ID,   U8_STORAGE_TYPE},
  {ATTRIBUTE_COMMAND_CLASS_SCENE_LOCAL_SCENES, "Local scenes", ATTRIBUTE_ENDPOINT_ID, EMPTY_STORAGE_TYPE},
  {ATTRIBUTE_COMMAND_CLASS_SCENE_ACTIVATION_ACTIVE_SCENE, "Active Scene", ATTRIBUTE_COMMAND_CLASS_SCENE_LOCAL_SCENES, U8_STORAGE_TYPE},
  {ATTRIBUTE_COMMAND_CLASS_SCENE_ACTIVATION_SETTING_DIMMING_DURATION, "Dimming Duration", ATTRIBUTE_COMMAND_CLASS_SCENE_ACTIVATION_ACTIVE_SCENE, U8_STORAGE_TYPE},
  /////////////////////////////////////////////////////////////////////
  //         Scene Actuator Configuration Command Class attributes
  /////////////////////////////////////////////////////////////////////
  {ATTRIBUTE_COMMAND_CLASS_SCENE_ACTUATOR_CONF_VERSION,   "Scene Actuator Configuration Command Class Version",   ATTRIBUTE_ENDPOINT_ID,   U8_STORAGE_TYPE},
  {ATTRIBUTE_COMMAND_CLASS_SCENE_ACTUATOR_CONFIGURATION, "Scene Actuator Configuration", ATTRIBUTE_COMMAND_CLASS_SCENE_LOCAL_SCENES, EMPTY_STORAGE_TYPE},
  {ATTRIBUTE_COMMAND_CLASS_SCENE_ACTUATOR_ID, "Scene ID", ATTRIBUTE_COMMAND_CLASS_SCENE_ACTUATOR_CONFIGURATION, U8_STORAGE_TYPE},
  {ATTRIBUTE_COMMAND_CLASS_SCENE_ACTUATOR_SETTING_DIMMING_DURATION, "Dimming Duration", ATTRIBUTE_COMMAND_CLASS_SCENE_ACTUATOR_ID, U8_STORAGE_TYPE},
  {ATTRIBUTE_COMMAND_CLASS_SCENE_ACTUATOR_SETTING_LEVEL, "Level", ATTRIBUTE_COMMAND_CLASS_SCENE_ACTUATOR_ID, U8_STORAGE_TYPE},
  {ATTRIBUTE_COMMAND_CLASS_SCENE_ACTUATOR_SETTING_OVERRIDE, "Override", ATTRIBUTE_COMMAND_CLASS_SCENE_ACTUATOR_ID, U8_STORAGE_TYPE},
  /////////////////////////////////////////////////////////////////////
  //         Scene Controller Configuration Command Class attributes
  /////////////////////////////////////////////////////////////////////
  {ATTRIBUTE_COMMAND_CLASS_SCENE_CONTROLLER_CONF_VERSION,   "Scene Controller Configuration Command Class Version",   ATTRIBUTE_ENDPOINT_ID,   U8_STORAGE_TYPE},
  {ATTRIBUTE_COMMAND_CLASS_SCENE_CONTROLLER_CONFIGURATION, "Scene Controller Configuration", ATTRIBUTE_COMMAND_CLASS_ASSOCIATION_GROUP_ID, ENUM_STORAGE_TYPE},
  {ATTRIBUTE_COMMAND_CLASS_SCENE_CONTROLLER_SETTING_ID, "Scene ID", ATTRIBUTE_COMMAND_CLASS_SCENE_CONTROLLER_CONFIGURATION, U8_STORAGE_TYPE},
  {ATTRIBUTE_COMMAND_CLASS_SCENE_CONTROLLER_SETTING_DIMMING_DURATION, "Dumming Duration", ATTRIBUTE_COMMAND_CLASS_SCENE_CONTROLLER_CONFIGURATION, U8_STORAGE_TYPE},
  /////////////////////////////////////////////////////////////////////
  //         Thermostat Operating State Command Class attributes
  /////////////////////////////////////////////////////////////////////
  {ATTRIBUTE_COMMAND_CLASS_THERMOSTAT_OPERATING_STATE_VERSION,   "Thermostat Operating State Version",   ATTRIBUTE_ENDPOINT_ID,   U8_STORAGE_TYPE},
  {ATTRIBUTE_COMMAND_CLASS_THERMOSTAT_OPERATING_STATE_CURRENT_STATE,   "Thermostat Operating State",   ATTRIBUTE_ENDPOINT_ID,   U8_STORAGE_TYPE},
  // V2
  {ATTRIBUTE_COMMAND_CLASS_THERMOSTAT_OPERATING_STATE_LOG_SUPPORTED_BITMASK,   "Thermostat Operating State Log Supported Count",   ATTRIBUTE_ENDPOINT_ID,   U32_STORAGE_TYPE},
  {ATTRIBUTE_COMMAND_CLASS_THERMOSTAT_OPERATING_STATE_LOG_SUPPORTED,   "Thermostat Operating State Log Supported",   ATTRIBUTE_COMMAND_CLASS_THERMOSTAT_OPERATING_STATE_LOG_SUPPORTED_BITMASK,   U8_STORAGE_TYPE},
  {ATTRIBUTE_COMMAND_CLASS_THERMOSTAT_OPERATING_STATE_LOG_BITMASK,   "Thermostat Operating State Log",   ATTRIBUTE_ENDPOINT_ID,   U32_STORAGE_TYPE},
  {ATTRIBUTE_COMMAND_CLASS_THERMOSTAT_OPERATING_STATE_LOG_STATE,   "Thermostat Operating State Log State",   ATTRIBUTE_COMMAND_CLASS_THERMOSTAT_OPERATING_STATE_LOG_BITMASK,   U8_STORAGE_TYPE},
  {ATTRIBUTE_COMMAND_CLASS_THERMOSTAT_OPERATING_STATE_LOG_USAGE_TODAY_HOURS,   "Thermostat Operating State Log Usage Today (Hours)",   ATTRIBUTE_COMMAND_CLASS_THERMOSTAT_OPERATING_STATE_LOG_STATE,   U8_STORAGE_TYPE},
  {ATTRIBUTE_COMMAND_CLASS_THERMOSTAT_OPERATING_STATE_LOG_USAGE_TODAY_MIN,   "Thermostat Operating State Log Usage Today (Min)",   ATTRIBUTE_COMMAND_CLASS_THERMOSTAT_OPERATING_STATE_LOG_STATE,   U8_STORAGE_TYPE},
  {ATTRIBUTE_COMMAND_CLASS_THERMOSTAT_OPERATING_STATE_LOG_USAGE_YESTERDAY_HOURS,   "Thermostat Operating State Log Usage Yesterday (Hours)",   ATTRIBUTE_COMMAND_CLASS_THERMOSTAT_OPERATING_STATE_LOG_STATE,   U8_STORAGE_TYPE},
  {ATTRIBUTE_COMMAND_CLASS_THERMOSTAT_OPERATING_STATE_LOG_USAGE_YESTERDAY_MIN,   "Thermostat Operating State Log Usage Yesterday (Hours)",   ATTRIBUTE_COMMAND_CLASS_THERMOSTAT_OPERATING_STATE_LOG_STATE,   U8_STORAGE_TYPE},
  /////////////////////////////////////////////////////////////////////
  //         Thermostat Fan State Command Class attributes
  /////////////////////////////////////////////////////////////////////
  {ATTRIBUTE_COMMAND_CLASS_THERMOSTAT_FAN_STATE_VERSION,   "Thermostat Fan State Version",   ATTRIBUTE_ENDPOINT_ID,   U8_STORAGE_TYPE},
  {ATTRIBUTE_COMMAND_CLASS_THERMOSTAT_FAN_STATE_FAN_OPERATING_STATE,   "Thermostat Fan Operating State",   ATTRIBUTE_ENDPOINT_ID,   U8_STORAGE_TYPE},
  /////////////////////////////////////////////////////////////////////
  //        Transport Service Command Class attributes
  //        Version is registered by command_class_transport_service
  /////////////////////////////////////////////////////////////////////
  /////////////////////////////////////////////////////////////////////
  //        User Code Command Class attributes
  /////////////////////////////////////////////////////////////////////
  {ATTRIBUTE_COMMAND_CLASS_USER_CODE_VERSION,   "User Code Version",   ATTRIBUTE_ENDPOINT_ID,   U8_STORAGE_TYPE},
  {ATTRIBUTE_COMMAND_CLASS_USER_CODE_DATA,   "User Code Data",   ATTRIBUTE_ENDPOINT_ID,   EMPTY_STORAGE_TYPE},
  {ATTRIBUTE_COMMAND_CLASS_USER_CODE_NUMBER_OF_USERS,   "Number of Users",   ATTRIBUTE_COMMAND_CLASS_USER_CODE_DATA,   U16_STORAGE_TYPE},
  {ATTRIBUTE_COMMAND_CLASS_USER_CODE_DELETE_ALL_REQUESTED,   "Delete all codes requested",   ATTRIBUTE_COMMAND_CLASS_USER_CODE_DATA,   ENUM_STORAGE_TYPE},
  {ATTRIBUTE_COMMAND_CLASS_USER_CODE_USER_ID,   "User ID",   ATTRIBUTE_COMMAND_CLASS_USER_CODE_DATA,   U16_STORAGE_TYPE},
  {ATTRIBUTE_COMMAND_CLASS_USER_CODE_CODE,   "Code",   ATTRIBUTE_COMMAND_CLASS_USER_CODE_USER_ID,  C_STRING_STORAGE_TYPE},
  {ATTRIBUTE_COMMAND_CLASS_USER_CODE_USER_ID_STATUS,   "Status",   ATTRIBUTE_COMMAND_CLASS_USER_CODE_USER_ID,  U8_STORAGE_TYPE},
  {ATTRIBUTE_COMMAND_CLASS_USER_CODE_ADMIN_CODE,   "Admin Code",   ATTRIBUTE_COMMAND_CLASS_USER_CODE_DATA,  C_STRING_STORAGE_TYPE},
  {ATTRIBUTE_COMMAND_CLASS_USER_CODE_CAPABILITIES,   "Capabilities",   ATTRIBUTE_COMMAND_CLASS_USER_CODE_DATA,   EMPTY_STORAGE_TYPE},
  {ATTRIBUTE_COMMAND_CLASS_USER_CODE_SUPPORTED_FLAGS,   "Supported Flags",   ATTRIBUTE_COMMAND_CLASS_USER_CODE_CAPABILITIES,  BYTE_ARRAY_STORAGE_TYPE},
  {ATTRIBUTE_COMMAND_CLASS_USER_CODE_SUPPORTED_USER_ID_STATUS,   "Supported User ID Status bitmask",   ATTRIBUTE_COMMAND_CLASS_USER_CODE_CAPABILITIES,  BYTE_ARRAY_STORAGE_TYPE},
  {ATTRIBUTE_COMMAND_CLASS_USER_CODE_SUPPORTED_KEYPAD_MODES,   "Supported Keypad Modes bitmask",   ATTRIBUTE_COMMAND_CLASS_USER_CODE_CAPABILITIES,  BYTE_ARRAY_STORAGE_TYPE},
  {ATTRIBUTE_COMMAND_CLASS_USER_CODE_SUPPORTED_KEYS,   "Supported Keys bitmask",   ATTRIBUTE_COMMAND_CLASS_USER_CODE_CAPABILITIES,  BYTE_ARRAY_STORAGE_TYPE},
  {ATTRIBUTE_COMMAND_CLASS_USER_CODE_CHECKSUM,   "User Code Checksum",   ATTRIBUTE_COMMAND_CLASS_USER_CODE_DATA,  U16_STORAGE_TYPE},
  {ATTRIBUTE_COMMAND_CLASS_USER_CODE_KEYPAD_MODE,   "Keypad Mode",   ATTRIBUTE_COMMAND_CLASS_USER_CODE_DATA,  U8_STORAGE_TYPE},
  /////////////////////////////////////////////////////////////////////
  //         Door Lock Command Class attributes
  /////////////////////////////////////////////////////////////////////
  // {ATTRIBUTE_COMMAND_CLASS_VERSION_VERSION,   "Version Command Class Version",   ATTRIBUTE_ENDPOINT_ID,   U8_STORAGE_TYPE},
  // {ATTRIBUTE_CC_VERSION_VERSION_REPORT_DATA,   "Version Report Data",   ATTRIBUTE_ENDPOINT_ID,   U8_STORAGE_TYPE},
  // {ATTRIBUTE_CC_VERSION_ZWAVE_LIBRARY_TYPE,   "Library type",   ATTRIBUTE_CC_VERSION_VERSION_REPORT_DATA,   U8_STORAGE_TYPE},
  // {ATTRIBUTE_CC_VERSION_ZWAVE_PROTOCOL_VERSION,   "Protocol Version",   ATTRIBUTE_CC_VERSION_VERSION_REPORT_DATA,   BYTE_ARRAY_STORAGE_TYPE},
  // {ATTRIBUTE_CC_VERSION_FIRMWARE,   "Firmware ID",   ATTRIBUTE_CC_VERSION_VERSION_REPORT_DATA,   U32_STORAGE_TYPE},
  // {ATTRIBUTE_CC_VERSION_FIRMWARE_VERSION,   "Firwmare Version",   ATTRIBUTE_CC_VERSION_FIRMWARE,   BYTE_ARRAY_STORAGE_TYPE},
  // {ATTRIBUTE_CC_VERSION_ZWAVE_SOFTWARE_GET_SUPPORT,   "Z-Wave Software Version Get Support",   ATTRIBUTE_ENDPOINT_ID,   U8_STORAGE_TYPE},
  // {ATTRIBUTE_CC_VERSION_SDK_VERSION,   "Z-Wave Software SDK Version",   ATTRIBUTE_ENDPOINT_ID,   BYTE_ARRAY_STORAGE_TYPE},
  // {ATTRIBUTE_CC_VERSION_APPLICATION_FRAMEWORK_API_VERSION,   "Z-Wave Software Application Framework Version",   ATTRIBUTE_ENDPOINT_ID,   BYTE_ARRAY_STORAGE_TYPE},
  // {ATTRIBUTE_CC_VERSION_APPLICATION_FRAMEWORK_BUILD_NUMBER,   "Z-Wave Software Application Framework Build Number",   ATTRIBUTE_ENDPOINT_ID,   BYTE_ARRAY_STORAGE_TYPE},
  // {ATTRIBUTE_CC_VERSION_HOST_INTERFACE_VERSION,   "Z-Wave Software Host Interface Version",   ATTRIBUTE_ENDPOINT_ID,   BYTE_ARRAY_STORAGE_TYPE},
  // {ATTRIBUTE_CC_VERSION_HOST_INTERFACE_BUILD_NUMBER,   "Z-Wave Software Host Interface Build Number",   ATTRIBUTE_ENDPOINT_ID,   BYTE_ARRAY_STORAGE_TYPE},
  // {ATTRIBUTE_CC_VERSION_ZWAVE_PROTOCOL_BUILD_NUMBER,   "Z-Wave Software Z-Wave Protocol Build Number",   ATTRIBUTE_ENDPOINT_ID,   BYTE_ARRAY_STORAGE_TYPE},
  // {ATTRIBUTE_CC_VERSION_APPLICATION_BUILD_NUMBER,   "Z-Wave Software Application Build Number",   ATTRIBUTE_ENDPOINT_ID,   BYTE_ARRAY_STORAGE_TYPE},
  // {ATTRIBUTE_CC_VERSION_HARDWARE_VERSION,   "Z-Wave Hardware Version",   ATTRIBUTE_CC_VERSION_VERSION_REPORT_DATA,   U32_STORAGE_TYPE},
  // {ATTRIBUTE_CC_VERSION_FOUND,   "Version CC is supported",   ATTRIBUTE_NODE_ID,   U8_STORAGE_TYPE},
  /////////////////////////////////////////////////////////////////////
  //         Firmware Update Command Class attributes
  /////////////////////////////////////////////////////////////////////
  // {ATTRIBUTE_COMMAND_CLASS_FWU_MD_VERSION,   "Firmware Update Version",   ATTRIBUTE_ENDPOINT_ID,   U8_STORAGE_TYPE},
  // {ATTRIBUTE_COMMAND_CLASS_FWU_MD_FWU,   "Firmware Update Meta Data Report",   ATTRIBUTE_ENDPOINT_ID,   I32_STORAGE_TYPE},
  // {ATTRIBUTE_COMMAND_CLASS_FWU_MD_FWU_FW,   "Firmware",   ATTRIBUTE_COMMAND_CLASS_FWU_MD_FWU,   I32_STORAGE_TYPE},
  // {ATTRIBUTE_COMMAND_CLASS_FWU_MD_FWU_FW_ID,   "Firmware ID",   ATTRIBUTE_COMMAND_CLASS_FWU_MD_FWU_FW,   I32_STORAGE_TYPE},
  // {ATTRIBUTE_COMMAND_CLASS_FWU_MD_FWU_FW_UPGRADABLE,   "Firmware Upgradable",   ATTRIBUTE_COMMAND_CLASS_FWU_MD_FWU_FW,   I32_STORAGE_TYPE},
  // {ATTRIBUTE_COMMAND_CLASS_FWU_MD_FWU_MANUFACTURER_ID,   "Manufacturer ID",   ATTRIBUTE_COMMAND_CLASS_FWU_MD_FWU,   I32_STORAGE_TYPE},
  // {ATTRIBUTE_COMMAND_CLASS_FWU_MD_FWU_FRAGMENT_SIZE,   "Max Fragment Size",   ATTRIBUTE_STORE_INVALID_ATTRIBUTE_TYPE,   I32_STORAGE_TYPE},
  // {ATTRIBUTE_COMMAND_CLASS_FWU_MD_FWU_ACTIVATION,   "Activation",   ATTRIBUTE_COMMAND_CLASS_FWU_MD_FWU,   I32_STORAGE_TYPE},
  // {ATTRIBUTE_COMMAND_CLASS_FWU_MD_FWU_CC,   "CC Capability",   ATTRIBUTE_COMMAND_CLASS_FWU_MD_FWU,   I32_STORAGE_TYPE},
  // {ATTRIBUTE_COMMAND_CLASS_FWU_MD_FW_TRANSFER,   "Firmware Transfer",   ATTRIBUTE_COMMAND_CLASS_FWU_MD_FWU,   ENUM_STORAGE_TYPE},
  // {ATTRIBUTE_COMMAND_CLASS_FWU_MD_FW_TRANSFER_TARGET,   "Firmware Target",   ATTRIBUTE_COMMAND_CLASS_FWU_MD_FW_TRANSFER,   ENUM_STORAGE_TYPE},
  // {ATTRIBUTE_COMMAND_CLASS_FWU_MD_FW_TRANSFER_APPLY_TIMESTAMP,   "Apply After Timestamp",   ATTRIBUTE_COMMAND_CLASS_FWU_MD_FW_TRANSFER,   UNSIGNED_LONG_STORAGE_TYPE},
  // {ATTRIBUTE_COMMAND_CLASS_FWU_MD_FW_TRANSFER_FILENAME,   "Filename",   ATTRIBUTE_COMMAND_CLASS_FWU_MD_FW_TRANSFER,   C_STRING_STORAGE_TYPE},
  // {ATTRIBUTE_COMMAND_CLASS_FWU_MD_FW_TRANSFER_OFFSET,   "Transfer Offset",   ATTRIBUTE_COMMAND_CLASS_FWU_MD_FW_TRANSFER,   U32_STORAGE_TYPE},
  // {ATTRIBUTE_COMMAND_CLASS_FWU_MD_FW_TRANSFER_SIZE,   "Transfer Size",   ATTRIBUTE_COMMAND_CLASS_FWU_MD_FW_TRANSFER,   U32_STORAGE_TYPE},
  // {ATTRIBUTE_COMMAND_CLASS_FWU_MD_FW_TRANSFER_LAST_STATUS,   "Transfer Last ",   ATTRIBUTE_COMMAND_CLASS_FWU_MD_FW_TRANSFER,   ENUM_STORAGE_TYPE},
  // {ATTRIBUTE_COMMAND_CLASS_FWU_MD_FW_TRANSFER_EXPIRY_TIME,   "Transfer Expiry Time",   ATTRIBUTE_COMMAND_CLASS_FWU_MD_FW_TRANSFER,   UNSIGNED_LONG_STORAGE_TYPE},
  /////////////////////////////////////////////////////////////////////
  //         Sound Switch Command Class attributes
  /////////////////////////////////////////////////////////////////////
  // {ATTRIBUTE_COMMAND_CLASS_SOUND_SWITCH_VERSION,   "Sound Switch Version",   ATTRIBUTE_ENDPOINT_ID,   U8_STORAGE_TYPE},
  // {ATTRIBUTE_COMMAND_CLASS_SOUND_SWITCH_CONFIGURED_DEFAULT_VOLUME,   "Configured Default Volume",   ATTRIBUTE_ENDPOINT_ID,   U8_STORAGE_TYPE},
  // {ATTRIBUTE_COMMAND_CLASS_SOUND_SWITCH_CONFIGURED_DEFAULT_TONE_IDENTIFIER,   "Configured Default Tone Identifier",   ATTRIBUTE_ENDPOINT_ID,   U8_STORAGE_TYPE},
  // {ATTRIBUTE_COMMAND_CLASS_SOUND_SWITCH_TONES_NUMBER,   "Tones Number",   ATTRIBUTE_ENDPOINT_ID,   U8_STORAGE_TYPE},
  // {ATTRIBUTE_COMMAND_CLASS_SOUND_SWITCH_TONE_INFO_IDENTIFIER,   "Tone Info Identifier",   ATTRIBUTE_COMMAND_CLASS_SOUND_SWITCH_TONES_NUMBER,   U8_STORAGE_TYPE},
  // {ATTRIBUTE_COMMAND_CLASS_SOUND_SWITCH_TONE_INFO_DURATION_SECONDS,   "Tone Info Duration Seconds",   ATTRIBUTE_COMMAND_CLASS_SOUND_SWITCH_TONE_INFO_IDENTIFIER,   U16_STORAGE_TYPE},
  // {ATTRIBUTE_COMMAND_CLASS_SOUND_SWITCH_TONE_INFO_NAME,   "Tone Info Name",   ATTRIBUTE_COMMAND_CLASS_SOUND_SWITCH_TONE_INFO_IDENTIFIER,   C_STRING_STORAGE_TYPE},
  // {ATTRIBUTE_COMMAND_CLASS_SOUND_SWITCH_TONE_PLAY, "Tone Play", ATTRIBUTE_ENDPOINT_ID, U8_STORAGE_TYPE},

  //DoorLock Command Class attributes
  // {ATTRIBUTE_DOOR_LOCK_CONFIGURATION_OPERATION_TYPE, "Door Lock Configuration Operation Type", ATTRIBUTE_ENDPOINT_ID, I32_STORAGE_TYPE },
  // {ATTRIBUTE_DOOR_LOCK_CONFIGURATION_INSIDE_DOOR_HANDLES_STATE, "Door Lock Configuration Inside Handles State", ATTRIBUTE_ENDPOINT_ID, I32_STORAGE_TYPE },
  // {ATTRIBUTE_DOOR_LOCK_CONFIGURATION_OUTSIDE_DOOR_HANDLES_STATE, "Door Lock Configuration Outside Handles State", ATTRIBUTE_ENDPOINT_ID, I32_STORAGE_TYPE },
  // {ATTRIBUTE_DOOR_LOCK_CONFIGURATION_LOCK_TIMEOUT_MINUTES, "Door Lock Configuration Lock Time Minutes", ATTRIBUTE_ENDPOINT_ID, I32_STORAGE_TYPE },
  // {ATTRIBUTE_DOOR_LOCK_CONFIGURATION_LOCK_TIMEOUT_SECONDS, "Door Lock Configuration Lock Time Seconds", ATTRIBUTE_ENDPOINT_ID, I32_STORAGE_TYPE },
  // {ATTRIBUTE_DOOR_LOCK_OPERATION_DOOR_LOCK_MODE, "Door Lock Configuration Lock Mode", ATTRIBUTE_ENDPOINT_ID, I32_STORAGE_TYPE },
  // {ATTRIBUTE_DOOR_LOCK_OPERATION_INSIDE_DOOR_HANDLES_MODE, "Door Lock Operation Inside Handles Mode", ATTRIBUTE_ENDPOINT_ID, I32_STORAGE_TYPE },
  // {ATTRIBUTE_DOOR_LOCK_OPERATION_OUTSIDE_DOOR_HANDLES_MODE, "Door Lock Operation Outside Hadles Mode", ATTRIBUTE_ENDPOINT_ID, I32_STORAGE_TYPE },
  // {ATTRIBUTE_DOOR_LOCK_OPERATION_DOOR_CONDITION, "Door Lock Operation Condition", ATTRIBUTE_ENDPOINT_ID, I32_STORAGE_TYPE },
  // {ATTRIBUTE_DOOR_LOCK_OPERATION_LOCK_TIMEOUT_MINUTES, "Door Lock Operation Lock Timeout Minutes", ATTRIBUTE_ENDPOINT_ID, I32_STORAGE_TYPE },
  // {ATTRIBUTE_DOOR_LOCK_OPERATION_LOCK_TIMEOUT_SECONDS, "Door Lock Operation Lock Timeout Seconds", ATTRIBUTE_ENDPOINT_ID, I32_STORAGE_TYPE },

};
// clang-format on

// This main function will serve as a registration bookkeeper for all our
// Z-Wave attributes
sl_status_t zpc_attribute_store_register_known_attribute_types()
{
    sl_status_t status = SL_STATUS_OK;
    for (auto const &a: attribute_schema) {
        status |= attribute_store_register_type(a.type, a.name, a.parent_type, a.storage_type);
    }
    return status;
}
